### ISSUE TITLE
Undefined is not an object (evaluating 'd.NativeModules.RNExitApp.exitApp')

### ISSUE THREAD

**Issue by maxsdev** [wumke/react-native-exit-app#9]
My android app crash on Android 4.4.2 when exitApp() is called.
`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.ctrack, PID: 10598
                                                   com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'd.NativeModules.RNExitApp.exitApp'), stack:
                                                   exitApp@1292:135
                                                   onPress@1289:2218
                                                   <unknown>@85:2292
                                                   value@18:5166
                                                   <unknown>@18:1480
                                                   value@18:3828
                                                   value@18:1450
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:149)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                       at java.lang.Thread.run(Thread.java:841)`
How can I fix it?

**Comment by wumke** [comment]
I've not seen this before, could it be that something went wrong with linking the native parts? Does it work on ios?

**Comment by maxsdev** [comment]
Yes, on iOS it's OK.

**Comment by stephane-r** [comment]
Same result on iOS

**Comment by wumke** [comment]
No typo's in the mainapplication.java file where you include the package?
Try cleaning and rebuilding, perhaps something went wrong (sometimes this actually helps to solve issues that are really weird!).
Seems to me like android does not know where to get the 'd.NativeModules.RNExitApp' from...

**Comment by wumke** [comment]
I've got a similar issue today with another package, rebuilding and reinstalling the app on the Android phone solved the problem for me!

**Comment by ramjak** [comment]
This is happen to me too. When I am rebuilding, there is an error that I need to install SDK build tool 25.0.0. It works after that.
